name: CI
on:
  push:
    branches: [ master ]
  #pull_request:
   # branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: cd /var/www/html/IRT-EFES && git pull && curl http://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@${{ secrets.HOST }}/admin/solr/index/all.html
